### ISSUE TITLE
Yaourt installation fails

### ISSUE THREAD

**Issue by mbareta** [cybre/budgie-screenshot-applet#42] opened 2018-07-09 11:48 UTC
When I try to install with yaourt, the archive cannot be downloaded because the server returns 404.

```
==> Building and installing package
==> Making package: budgie-screenshot-applet 0.4.3-0.1 (ponedjeljak, 09. srpnja 2018. 13:45:20 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading 0.4.3.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   137    0   137    0     0    142      0 --:--:-- --:--:-- --:--:--   142
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading https://github.com/cybre/budgie-screenshot-applet/archive/0.4.3.tar.gz
    Aborting...
```

**Comment by fossfreedom** [comment] 2018-07-09 12:09
your yaourt package needs updating - the tarball now has a "v" prefix i.e. v0.4.3

**Comment by cybre** [comment] 2018-07-09 14:30
Duplicate of #41 
Again, I am not the maintainer of the AUR package.
I am not responsible for breakage there.

**Closed as completed by cybre** 2018-07-09 14:30 UTC
